<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>AudioBridgeRenderer</AssemblyName>
    <RootNamespace>AudioBridge.Renderer</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyToPlugins>true</CopyToPlugins>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Remove="**/*.cs" />
    <Compile Include="AudioBridgeRenderer.cs" />
  </ItemGroup>

  <PropertyGroup>
    <GamePath Condition="Exists('/mnt/c/Program Files (x86)/Steam/steamapps/common/Resonite/')">/mnt/c/Program Files (x86)/Steam/steamapps/common/Resonite/</GamePath>
    <GamePath Condition="Exists('G:\SteamLibrary\steamapps\common\Resonite\')">G:\SteamLibrary\steamapps\common\Resonite\</GamePath>
    <PluginTargetDir>$(GamePath)Renderer\BepInEx\plugins\$(AssemblyName)</PluginTargetDir>
  </PropertyGroup>

  <ItemGroup>
    <!-- BepInEx 5 -->
    <Reference Include="BepInEx">
      <HintPath>$(GamePath)Renderer/BepInEx/core/BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    
    <!-- Harmony -->
    <Reference Include="0Harmony">
      <HintPath>$(GamePath)Renderer/BepInEx/core/0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    
    <!-- Unity -->
    <Reference Include="UnityEngine">
      <HintPath>$(GamePath)Renderer/Renderite.Renderer_Data/Managed/UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GamePath)Renderer/Renderite.Renderer_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="InterprocessLib.Unity">
        <HintPath>$(GamePath)Renderer\BepInEx\plugins\Nytra-InterprocessLib\plugins\InterprocessLib.BepInEx\InterprocessLib.Unity.dll</HintPath>
        <Private>False</Private>
    </Reference>
    <Reference Include="Renderite.Shared">
        <HintPath>$(GamePath)Renderer/Renderite.Renderer_Data/Managed/Renderite.Shared.dll</HintPath>
        <Private>False</Private>
    </Reference>
    <!-- CSCore (copy to plugin folder) -->
    <Reference Include="CSCore">
      <HintPath>$(GamePath)CSCore.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <ItemGroup>
            <PluginFiles Include="$(TargetPath)" />
            <PluginFiles Include="$(TargetDir)$(TargetName).pdb" Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
        </ItemGroup>
        
        <Copy SourceFiles="@(PluginFiles)" DestinationFolder="$(PluginTargetDir)" Condition="'$(CopyToPlugins)' == 'true'" />
        <Message Text="Copied plugin files to $(PluginTargetDir)" Importance="high" Condition="'$(CopyToPlugins)' == 'true'" />
    </Target>
</Project>